### PR TITLE
Improved "ok" validation

### PR DESCRIPTION
**Pull request by alexl4123**
- I reduced the max length of the line when validating for ''ok''
- I added this, because my error email contains the word ''lookup'', which contains ''ok'', which means it fails at user 100 -> As I suppose that a few more people will have this problem, I reduced the length of the ''ok'' validation

### CODE REVIEW

**Comment by flofriday** [comment]
Thank you for the fix.

I haven't really looked at that code before but wouldn't it be a better fix if if we look if the line starts with `ok`?

Example:
```python
if line.startswith("ok"):
                print(...
```

**Comment by alexl4123** [comment]
Yeah, this would even be better and I just tested it locally with line.startswith - works :-)
There are other "ok" validations too - so I would propose to improve them too, with line.startswith(...

**Comment by flofriday** [comment]
Sounds good I will quickly fix them 👍

**Comment by alexl4123** [comment]
Ok, otherwise I can also fix them (actually already have locally), would just need to test & push :-)

**Comment by flofriday** [comment]
Oh I am so sorry, I just saw you message now. 😔

But could you maybe verify that it still works?
This would help me a lot as I have to leave now and I also added 1-2 other features real quick 😅

**Pull request merged**
